//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET/", ConfigurationName="ServiceReference2.CookingUnitSoap")]
    public interface CookingUnitSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/ChangeCookingUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double ChangeCookingUnit(double CookingValue, WindowsFormsApplication2.ServiceReference2.Cookings fromCookingUnit, WindowsFormsApplication2.ServiceReference2.Cookings toCookingUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/ChangeCookingUnit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> ChangeCookingUnitAsync(double CookingValue, WindowsFormsApplication2.ServiceReference2.Cookings fromCookingUnit, WindowsFormsApplication2.ServiceReference2.Cookings toCookingUnit);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webserviceX.NET/")]
    public enum Cookings {
        
        /// <remarks/>
        drop,
        
        /// <remarks/>
        dash,
        
        /// <remarks/>
        pinch,
        
        /// <remarks/>
        milliliterPerCC,
        
        /// <remarks/>
        deciliter,
        
        /// <remarks/>
        coffeeSpoon,
        
        /// <remarks/>
        fluidDram,
        
        /// <remarks/>
        teaspoonUS,
        
        /// <remarks/>
        teaspoonUK,
        
        /// <remarks/>
        tablespoonUS,
        
        /// <remarks/>
        tablespoonUK,
        
        /// <remarks/>
        fluidOunceUS,
        
        /// <remarks/>
        fluidOunceUK,
        
        /// <remarks/>
        cupUS,
        
        /// <remarks/>
        cubicInch,
        
        /// <remarks/>
        gillUS,
        
        /// <remarks/>
        gillUK,
        
        /// <remarks/>
        pintUS,
        
        /// <remarks/>
        pintUK,
        
        /// <remarks/>
        quartUS,
        
        /// <remarks/>
        liter,
        
        /// <remarks/>
        gallonUS,
        
        /// <remarks/>
        gallonUK,
        
        /// <remarks/>
        TwoPointFiveCan,
        
        /// <remarks/>
        TenCan,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CookingUnitSoapChannel : WindowsFormsApplication2.ServiceReference2.CookingUnitSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CookingUnitSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication2.ServiceReference2.CookingUnitSoap>, WindowsFormsApplication2.ServiceReference2.CookingUnitSoap {
        
        public CookingUnitSoapClient() {
        }
        
        public CookingUnitSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CookingUnitSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CookingUnitSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CookingUnitSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ChangeCookingUnit(double CookingValue, WindowsFormsApplication2.ServiceReference2.Cookings fromCookingUnit, WindowsFormsApplication2.ServiceReference2.Cookings toCookingUnit) {
            return base.Channel.ChangeCookingUnit(CookingValue, fromCookingUnit, toCookingUnit);
        }
        
        public System.Threading.Tasks.Task<double> ChangeCookingUnitAsync(double CookingValue, WindowsFormsApplication2.ServiceReference2.Cookings fromCookingUnit, WindowsFormsApplication2.ServiceReference2.Cookings toCookingUnit) {
            return base.Channel.ChangeCookingUnitAsync(CookingValue, fromCookingUnit, toCookingUnit);
        }
    }
}
