//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatUpService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Submitter { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> TimeSubmitted { get; set; }
        public int ChatRoomId { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
    }
}
